name: Build Kernel
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/samsung-sm8450-kernel/android_kernel_samsung_sm8450
          kernel-branch: main
          config: r0q_defconfig
          arch: arm64
          aosp-clang: true
          aosp-clang-version: r416183b
          aosp-gcc: true
          android-version: 12
          ksu: true
          anykernel3: true
          extra-make-args: "CONFIG_CFG80211=y CONFIG_MAC80211=y CONFIG_USB_NET_DRIVERS=y CONFIG_USB_USBNET=y CONFIG_USB_GADGET=y"
      - uses: actions/upload-artifact@v4
        with:
          name: Heinrich-S901E-Kernel
          path: out/arch/arm64/boot/Image*
